//
//  StyleKit.swift
//  CasinoVenezia
//
//  Created by Massimo Moro on 09/02/2018.
//  Copyright © 2018 CMV Gioco Spa. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class StyleKit : NSObject {

    //// Cache

    private struct Cache {
        static let fillColor: UIColor = UIColor(red: 0.518, green: 0.459, blue: 0.322, alpha: 1.000)
    }

    //// Colors

    @objc dynamic public class var fillColor: UIColor { return Cache.fillColor }

    //// Drawing Methods

    @objc dynamic public class func drawIconaDove(frame: CGRect = CGRect(x: 0, y: 0, width: 100, height: 100)) {

        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: frame.minX + 0.50974 * frame.width, y: frame.minY + 0.21761 * frame.height))
        bezier2Path.addLine(to: CGPoint(x: frame.minX + 0.50885 * frame.width, y: frame.minY + 0.21761 * frame.height))
        bezier2Path.addCurve(to: CGPoint(x: frame.minX + 0.38227 * frame.width, y: frame.minY + 0.34465 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.43895 * frame.width, y: frame.minY + 0.21761 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.38227 * frame.width, y: frame.minY + 0.27449 * frame.height))
        bezier2Path.addCurve(to: CGPoint(x: frame.minX + 0.50885 * frame.width, y: frame.minY + 0.47170 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.38227 * frame.width, y: frame.minY + 0.41482 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.43895 * frame.width, y: frame.minY + 0.47170 * frame.height))
        bezier2Path.addCurve(to: CGPoint(x: frame.minX + 0.63543 * frame.width, y: frame.minY + 0.34465 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.57876 * frame.width, y: frame.minY + 0.47170 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.63543 * frame.width, y: frame.minY + 0.41482 * frame.height))
        bezier2Path.addCurve(to: CGPoint(x: frame.minX + 0.63541 * frame.width, y: frame.minY + 0.34244 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.63543 * frame.width, y: frame.minY + 0.34391 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.63543 * frame.width, y: frame.minY + 0.34317 * frame.height))
        bezier2Path.addLine(to: CGPoint(x: frame.minX + 0.63543 * frame.width, y: frame.minY + 0.34465 * frame.height))
        bezier2Path.addCurve(to: CGPoint(x: frame.minX + 0.51106 * frame.width, y: frame.minY + 0.21763 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.63543 * frame.width, y: frame.minY + 0.27535 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.58010 * frame.width, y: frame.minY + 0.21884 * frame.height))
        bezier2Path.addLine(to: CGPoint(x: frame.minX + 0.50974 * frame.width, y: frame.minY + 0.21761 * frame.height))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: frame.minX + 0.50974 * frame.width, y: frame.minY + 0.43532 * frame.height))
        bezier2Path.addLine(to: CGPoint(x: frame.minX + 0.50974 * frame.width, y: frame.minY + 0.43532 * frame.height))
        bezier2Path.addCurve(to: CGPoint(x: frame.minX + 0.42060 * frame.width, y: frame.minY + 0.34585 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.46051 * frame.width, y: frame.minY + 0.43532 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.42060 * frame.width, y: frame.minY + 0.39526 * frame.height))
        bezier2Path.addCurve(to: CGPoint(x: frame.minX + 0.50974 * frame.width, y: frame.minY + 0.25638 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.42060 * frame.width, y: frame.minY + 0.29644 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.46051 * frame.width, y: frame.minY + 0.25638 * frame.height))
        bezier2Path.addCurve(to: CGPoint(x: frame.minX + 0.59889 * frame.width, y: frame.minY + 0.34585 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.55898 * frame.width, y: frame.minY + 0.25638 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.59889 * frame.width, y: frame.minY + 0.29644 * frame.height))
        bezier2Path.addLine(to: CGPoint(x: frame.minX + 0.59889 * frame.width, y: frame.minY + 0.34585 * frame.height))
        bezier2Path.addCurve(to: CGPoint(x: frame.minX + 0.50974 * frame.width, y: frame.minY + 0.43532 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.59889 * frame.width, y: frame.minY + 0.39526 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.55898 * frame.width, y: frame.minY + 0.43532 * frame.height))
        bezier2Path.close()
        StyleKit.fillColor.setFill()
        bezier2Path.fill()


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: frame.minX + 0.75161 * frame.width, y: frame.minY + 0.10190 * frame.height))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 0.75161 * frame.width, y: frame.minY + 0.10190 * frame.height))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 0.26164 * frame.width, y: frame.minY + 0.10190 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.61631 * frame.width, y: frame.minY + -0.03390 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.39694 * frame.width, y: frame.minY + -0.03390 * frame.height))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 0.22895 * frame.width, y: frame.minY + 0.59039 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.14040 * frame.width, y: frame.minY + 0.22328 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.12525 * frame.width, y: frame.minY + 0.45202 * frame.height))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 0.50648 * frame.width, y: frame.minY + 0.99300 * frame.height))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 0.78400 * frame.width, y: frame.minY + 0.59099 * frame.height))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 0.75191 * frame.width, y: frame.minY + 0.10160 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.88800 * frame.width, y: frame.minY + 0.45202 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.87314 * frame.width, y: frame.minY + 0.22328 * frame.height))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 0.75161 * frame.width, y: frame.minY + 0.10190 * frame.height))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: frame.minX + 0.75459 * frame.width, y: frame.minY + 0.57012 * frame.height))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 0.50677 * frame.width, y: frame.minY + 0.92799 * frame.height))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 0.25807 * frame.width, y: frame.minY + 0.56922 * frame.height))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 0.28719 * frame.width, y: frame.minY + 0.12755 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.16418 * frame.width, y: frame.minY + 0.44367 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.17784 * frame.width, y: frame.minY + 0.23849 * frame.height))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 0.28632 * frame.width, y: frame.minY + 0.12842 * frame.height))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 0.72544 * frame.width, y: frame.minY + 0.12842 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.40758 * frame.width, y: frame.minY + 0.00671 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.60418 * frame.width, y: frame.minY + 0.00671 * frame.height))
        bezierPath.addCurve(to: CGPoint(x: frame.minX + 0.75429 * frame.width, y: frame.minY + 0.57012 * frame.height), controlPoint1: CGPoint(x: frame.minX + 0.83392 * frame.width, y: frame.minY + 0.23729 * frame.height), controlPoint2: CGPoint(x: frame.minX + 0.84729 * frame.width, y: frame.minY + 0.44367 * frame.height))
        bezierPath.addLine(to: CGPoint(x: frame.minX + 0.75459 * frame.width, y: frame.minY + 0.57012 * frame.height))
        bezierPath.close()
        StyleKit.fillColor.setFill()
        bezierPath.fill()
    }

    @objc dynamic public class func drawIconaQuando(frame: CGRect = CGRect(x: 0, y: 0, width: 100, height: 100)) {
        //// Color Declarations
        let strokeColor = UIColor(red: 0.518, green: 0.459, blue: 0.322, alpha: 1.000)


        //// Subframes
        let livello_2: CGRect = CGRect(x: frame.minX + 3.13, y: frame.minY + 2.13, width: frame.width - 6.04, height: frame.height - 6.04)


        //// Livello_2
        //// Livello_1-2
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: livello_2.minX + 0.50000 * livello_2.width, y: livello_2.minY + 0.00000 * livello_2.height))
        bezierPath.addLine(to: CGPoint(x: livello_2.minX + 0.50000 * livello_2.width, y: livello_2.minY + 0.00000 * livello_2.height))
        bezierPath.addCurve(to: CGPoint(x: livello_2.minX + 0.00000 * livello_2.width, y: livello_2.minY + 0.50000 * livello_2.height), controlPoint1: CGPoint(x: livello_2.minX + 0.22386 * livello_2.width, y: livello_2.minY + 0.00000 * livello_2.height), controlPoint2: CGPoint(x: livello_2.minX + 0.00000 * livello_2.width, y: livello_2.minY + 0.22386 * livello_2.height))
        bezierPath.addCurve(to: CGPoint(x: livello_2.minX + 0.50000 * livello_2.width, y: livello_2.minY + 1.00000 * livello_2.height), controlPoint1: CGPoint(x: livello_2.minX + 0.00000 * livello_2.width, y: livello_2.minY + 0.77614 * livello_2.height), controlPoint2: CGPoint(x: livello_2.minX + 0.22386 * livello_2.width, y: livello_2.minY + 1.00000 * livello_2.height))
        bezierPath.addCurve(to: CGPoint(x: livello_2.minX + 1.00000 * livello_2.width, y: livello_2.minY + 0.50000 * livello_2.height), controlPoint1: CGPoint(x: livello_2.minX + 0.77614 * livello_2.width, y: livello_2.minY + 1.00000 * livello_2.height), controlPoint2: CGPoint(x: livello_2.minX + 1.00000 * livello_2.width, y: livello_2.minY + 0.77614 * livello_2.height))
        bezierPath.addLine(to: CGPoint(x: livello_2.minX + 1.00000 * livello_2.width, y: livello_2.minY + 0.50059 * livello_2.height))
        bezierPath.addCurve(to: CGPoint(x: livello_2.minX + 0.49941 * livello_2.width, y: livello_2.minY + 0.00000 * livello_2.height), controlPoint1: CGPoint(x: livello_2.minX + 1.00000 * livello_2.width, y: livello_2.minY + 0.22412 * livello_2.height), controlPoint2: CGPoint(x: livello_2.minX + 0.77588 * livello_2.width, y: livello_2.minY + 0.00000 * livello_2.height))
        bezierPath.addLine(to: CGPoint(x: livello_2.minX + 0.50000 * livello_2.width, y: livello_2.minY + 0.00000 * livello_2.height))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: livello_2.minX + 0.50000 * livello_2.width, y: livello_2.minY + 0.96698 * livello_2.height))
        bezierPath.addLine(to: CGPoint(x: livello_2.minX + 0.50000 * livello_2.width, y: livello_2.minY + 0.96698 * livello_2.height))
        bezierPath.addCurve(to: CGPoint(x: livello_2.minX + 0.03302 * livello_2.width, y: livello_2.minY + 0.50000 * livello_2.height), controlPoint1: CGPoint(x: livello_2.minX + 0.24209 * livello_2.width, y: livello_2.minY + 0.96698 * livello_2.height), controlPoint2: CGPoint(x: livello_2.minX + 0.03302 * livello_2.width, y: livello_2.minY + 0.75791 * livello_2.height))
        bezierPath.addCurve(to: CGPoint(x: livello_2.minX + 0.50000 * livello_2.width, y: livello_2.minY + 0.03302 * livello_2.height), controlPoint1: CGPoint(x: livello_2.minX + 0.03302 * livello_2.width, y: livello_2.minY + 0.24209 * livello_2.height), controlPoint2: CGPoint(x: livello_2.minX + 0.24209 * livello_2.width, y: livello_2.minY + 0.03302 * livello_2.height))
        bezierPath.addCurve(to: CGPoint(x: livello_2.minX + 0.96698 * livello_2.width, y: livello_2.minY + 0.50000 * livello_2.height), controlPoint1: CGPoint(x: livello_2.minX + 0.75791 * livello_2.width, y: livello_2.minY + 0.03302 * livello_2.height), controlPoint2: CGPoint(x: livello_2.minX + 0.96698 * livello_2.width, y: livello_2.minY + 0.24209 * livello_2.height))
        bezierPath.addLine(to: CGPoint(x: livello_2.minX + 0.96698 * livello_2.width, y: livello_2.minY + 0.50000 * livello_2.height))
        bezierPath.addCurve(to: CGPoint(x: livello_2.minX + 0.50000 * livello_2.width, y: livello_2.minY + 0.96698 * livello_2.height), controlPoint1: CGPoint(x: livello_2.minX + 0.96698 * livello_2.width, y: livello_2.minY + 0.75791 * livello_2.height), controlPoint2: CGPoint(x: livello_2.minX + 0.75791 * livello_2.width, y: livello_2.minY + 0.96698 * livello_2.height))
        bezierPath.close()
        StyleKit.fillColor.setFill()
        bezierPath.fill()
        strokeColor.setStroke()
        bezierPath.lineWidth = 0.5
        bezierPath.stroke()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: livello_2.minX + 0.50000 * livello_2.width, y: livello_2.minY + 0.09965 * livello_2.height))
        bezier2Path.addLine(to: CGPoint(x: livello_2.minX + 0.50000 * livello_2.width, y: livello_2.minY + 0.09965 * livello_2.height))
        bezier2Path.addCurve(to: CGPoint(x: livello_2.minX + 0.48349 * livello_2.width, y: livello_2.minY + 0.11616 * livello_2.height), controlPoint1: CGPoint(x: livello_2.minX + 0.49088 * livello_2.width, y: livello_2.minY + 0.09965 * livello_2.height), controlPoint2: CGPoint(x: livello_2.minX + 0.48349 * livello_2.width, y: livello_2.minY + 0.10704 * livello_2.height))
        bezier2Path.addLine(to: CGPoint(x: livello_2.minX + 0.48349 * livello_2.width, y: livello_2.minY + 0.49941 * livello_2.height))
        bezier2Path.addLine(to: CGPoint(x: livello_2.minX + 0.23290 * livello_2.width, y: livello_2.minY + 0.49941 * livello_2.height))
        bezier2Path.addLine(to: CGPoint(x: livello_2.minX + 0.23290 * livello_2.width, y: livello_2.minY + 0.49941 * livello_2.height))
        bezier2Path.addCurve(to: CGPoint(x: livello_2.minX + 0.21610 * livello_2.width, y: livello_2.minY + 0.51621 * livello_2.height), controlPoint1: CGPoint(x: livello_2.minX + 0.22362 * livello_2.width, y: livello_2.minY + 0.49941 * livello_2.height), controlPoint2: CGPoint(x: livello_2.minX + 0.21610 * livello_2.width, y: livello_2.minY + 0.50693 * livello_2.height))
        bezier2Path.addCurve(to: CGPoint(x: livello_2.minX + 0.23290 * livello_2.width, y: livello_2.minY + 0.53302 * livello_2.height), controlPoint1: CGPoint(x: livello_2.minX + 0.21610 * livello_2.width, y: livello_2.minY + 0.52550 * livello_2.height), controlPoint2: CGPoint(x: livello_2.minX + 0.22362 * livello_2.width, y: livello_2.minY + 0.53302 * livello_2.height))
        bezier2Path.addLine(to: CGPoint(x: livello_2.minX + 0.50000 * livello_2.width, y: livello_2.minY + 0.53302 * livello_2.height))
        bezier2Path.addLine(to: CGPoint(x: livello_2.minX + 0.50000 * livello_2.width, y: livello_2.minY + 0.53302 * livello_2.height))
        bezier2Path.addCurve(to: CGPoint(x: livello_2.minX + 0.51651 * livello_2.width, y: livello_2.minY + 0.51651 * livello_2.height), controlPoint1: CGPoint(x: livello_2.minX + 0.50912 * livello_2.width, y: livello_2.minY + 0.53302 * livello_2.height), controlPoint2: CGPoint(x: livello_2.minX + 0.51651 * livello_2.width, y: livello_2.minY + 0.52563 * livello_2.height))
        bezier2Path.addLine(to: CGPoint(x: livello_2.minX + 0.51651 * livello_2.width, y: livello_2.minY + 0.11616 * livello_2.height))
        bezier2Path.addLine(to: CGPoint(x: livello_2.minX + 0.51651 * livello_2.width, y: livello_2.minY + 0.11616 * livello_2.height))
        bezier2Path.addCurve(to: CGPoint(x: livello_2.minX + 0.50000 * livello_2.width, y: livello_2.minY + 0.09965 * livello_2.height), controlPoint1: CGPoint(x: livello_2.minX + 0.51651 * livello_2.width, y: livello_2.minY + 0.10704 * livello_2.height), controlPoint2: CGPoint(x: livello_2.minX + 0.50912 * livello_2.width, y: livello_2.minY + 0.09965 * livello_2.height))
        bezier2Path.close()
        StyleKit.fillColor.setFill()
        bezier2Path.fill()
        strokeColor.setStroke()
        bezier2Path.lineWidth = 0.5
        bezier2Path.stroke()
    }

    @objc dynamic public class func drawEvents(frame: CGRect = CGRect(x: 0, y: 1, width: 97, height: 99), highlited: Bool = true) {
        //// General Declarations
        // This non-generic function dramatically improves compilation times of complex expressions.
        func fastFloor(_ x: CGFloat) -> CGFloat { return floor(x) }

        //// Color Declarations
        let bianco = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let rosso = UIColor(red: 0.888, green: 0.030, blue: 0.030, alpha: 1.000)


        //// Subframes
        let group: CGRect = CGRect(x: frame.minX + 2.5, y: frame.minY + 0.5, width: frame.width - 2.66, height: frame.height - 1)


        //// Group
        //// Rectangle 2 Drawing
        let rectangle2Path = UIBezierPath(rect: CGRect(x: group.minX + fastFloor(group.width * 0.14841 + 0.5), y: group.minY + fastFloor(group.height * 0.00000 + 0.5), width: fastFloor(group.width * 0.26501 + 0.5) - fastFloor(group.width * 0.14841 + 0.5), height: fastFloor(group.height * 0.18367 + 0.5) - fastFloor(group.height * 0.00000 + 0.5)))
        bianco.setStroke()
        rectangle2Path.lineWidth = 2
        rectangle2Path.lineJoinStyle = .round
        rectangle2Path.stroke()


        //// Rectangle 4 Drawing
        let rectangle4Path = UIBezierPath()
        rectangle4Path.move(to: CGPoint(x: group.minX + 0.94004 * group.width, y: group.minY + 0.54054 * group.height))
        rectangle4Path.addLine(to: CGPoint(x: group.minX + 0.93438 * group.width, y: group.minY + 0.08434 * group.height))
        rectangle4Path.addLine(to: CGPoint(x: group.minX + 0.83611 * group.width, y: group.minY + 0.08434 * group.height))
        rectangle4Path.move(to: CGPoint(x: group.minX + 0.09381 * group.width, y: group.minY + 0.08108 * group.height))
        rectangle4Path.addLine(to: CGPoint(x: group.minX + 0.00000 * group.width, y: group.minY + 0.08108 * group.height))
        rectangle4Path.addLine(to: CGPoint(x: group.minX + 0.00000 * group.width, y: group.minY + 1.00000 * group.height))
        rectangle4Path.addLine(to: CGPoint(x: group.minX + 0.48384 * group.width, y: group.minY + 1.00000 * group.height))
        rectangle4Path.move(to: CGPoint(x: group.minX + 0.67178 * group.width, y: group.minY + 0.07865 * group.height))
        rectangle4Path.addLine(to: CGPoint(x: group.minX + 0.27798 * group.width, y: group.minY + 0.07865 * group.height))
        bianco.setStroke()
        rectangle4Path.lineWidth = 2
        rectangle4Path.lineCapStyle = .round
        rectangle4Path.lineJoinStyle = .round
        rectangle4Path.stroke()


        //// Bezier 6 Drawing
        let bezier6Path = UIBezierPath()
        bezier6Path.move(to: CGPoint(x: group.minX + 0.01284 * group.width, y: group.minY + 0.24495 * group.height))
        bezier6Path.addCurve(to: CGPoint(x: group.minX + 0.93906 * group.width, y: group.minY + 0.24495 * group.height), controlPoint1: CGPoint(x: group.minX + 0.08333 * group.width, y: group.minY + 0.24495 * group.height), controlPoint2: CGPoint(x: group.minX + 0.93906 * group.width, y: group.minY + 0.24495 * group.height))
        UIColor.red.setFill()
        bezier6Path.fill()
        bianco.setStroke()
        bezier6Path.lineWidth = 2
        bezier6Path.stroke()


        //// Bezier 7 Drawing
        let bezier7Path = UIBezierPath()
        bezier7Path.move(to: CGPoint(x: group.minX + 0.81379 * group.width, y: group.minY + 0.53783 * group.height))
        bezier7Path.addLine(to: CGPoint(x: group.minX + 0.81379 * group.width, y: group.minY + 0.38183 * group.height))
        bezier7Path.addLine(to: CGPoint(x: group.minX + 0.14126 * group.width, y: group.minY + 0.37822 * group.height))
        bezier7Path.addLine(to: CGPoint(x: group.minX + 0.14126 * group.width, y: group.minY + 0.86284 * group.height))
        bezier7Path.addLine(to: CGPoint(x: group.minX + 0.48687 * group.width, y: group.minY + 0.86284 * group.height))
        bezier7Path.move(to: CGPoint(x: group.minX + 0.32098 * group.width, y: group.minY + 0.37822 * group.height))
        bezier7Path.addCurve(to: CGPoint(x: group.minX + 0.32098 * group.width, y: group.minY + 0.87624 * group.height), controlPoint1: CGPoint(x: group.minX + 0.32098 * group.width, y: group.minY + 0.88748 * group.height), controlPoint2: CGPoint(x: group.minX + 0.32098 * group.width, y: group.minY + 0.87624 * group.height))
        bezier7Path.addLine(to: CGPoint(x: group.minX + 0.32098 * group.width, y: group.minY + 0.37822 * group.height))
        bezier7Path.close()
        bezier7Path.move(to: CGPoint(x: group.minX + 0.48687 * group.width, y: group.minY + 0.37822 * group.height))
        bezier7Path.addCurve(to: CGPoint(x: group.minX + 0.48687 * group.width, y: group.minY + 0.87624 * group.height), controlPoint1: CGPoint(x: group.minX + 0.48687 * group.width, y: group.minY + 0.88765 * group.height), controlPoint2: CGPoint(x: group.minX + 0.48687 * group.width, y: group.minY + 0.87624 * group.height))
        bezier7Path.addLine(to: CGPoint(x: group.minX + 0.48687 * group.width, y: group.minY + 0.37822 * group.height))
        bezier7Path.close()
        bezier7Path.move(to: CGPoint(x: group.minX + 0.65276 * group.width, y: group.minY + 0.37822 * group.height))
        bezier7Path.addLine(to: CGPoint(x: group.minX + 0.65276 * group.width, y: group.minY + 0.55244 * group.height))
        bezier7Path.addLine(to: CGPoint(x: group.minX + 0.65276 * group.width, y: group.minY + 0.37822 * group.height))
        bezier7Path.close()
        bezier7Path.move(to: CGPoint(x: group.minX + 0.14126 * group.width, y: group.minY + 0.53904 * group.height))
        bezier7Path.addCurve(to: CGPoint(x: group.minX + 0.81379 * group.width, y: group.minY + 0.53783 * group.height), controlPoint1: CGPoint(x: group.minX + 0.81991 * group.width, y: group.minY + 0.53904 * group.height), controlPoint2: CGPoint(x: group.minX + 0.81379 * group.width, y: group.minY + 0.53783 * group.height))
        bezier7Path.addLine(to: CGPoint(x: group.minX + 0.14126 * group.width, y: group.minY + 0.53904 * group.height))
        bezier7Path.close()
        bezier7Path.move(to: CGPoint(x: group.minX + 0.15509 * group.width, y: group.minY + 0.69985 * group.height))
        bezier7Path.addCurve(to: CGPoint(x: group.minX + 0.48687 * group.width, y: group.minY + 0.69985 * group.height), controlPoint1: CGPoint(x: group.minX + 0.14126 * group.width, y: group.minY + 0.69985 * group.height), controlPoint2: CGPoint(x: group.minX + 0.48687 * group.width, y: group.minY + 0.69985 * group.height))
        bezier7Path.addLine(to: CGPoint(x: group.minX + 0.15509 * group.width, y: group.minY + 0.69985 * group.height))
        bezier7Path.close()
        bianco.setStroke()
        bezier7Path.lineWidth = 2
        bezier7Path.lineCapStyle = .square
        bezier7Path.stroke()


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: group.minX + 0.67047 * group.width, y: group.minY + 0.91216 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.57939 * group.width, y: group.minY + 0.66186 * group.height), controlPoint1: CGPoint(x: group.minX + 0.57341 * group.width, y: group.minY + 0.84209 * group.height), controlPoint2: CGPoint(x: group.minX + 0.51196 * group.width, y: group.minY + 0.75413 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.72152 * group.width, y: group.minY + 0.63150 * group.height), controlPoint1: CGPoint(x: group.minX + 0.62104 * group.width, y: group.minY + 0.61201 * group.height), controlPoint2: CGPoint(x: group.minX + 0.68022 * group.width, y: group.minY + 0.60644 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.77761 * group.width, y: group.minY + 0.69667 * group.height), controlPoint1: CGPoint(x: group.minX + 0.73959 * group.width, y: group.minY + 0.64189 * group.height), controlPoint2: CGPoint(x: group.minX + 0.77058 * group.width, y: group.minY + 0.68496 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.86055 * group.width, y: group.minY + 0.62080 * group.height), controlPoint1: CGPoint(x: group.minX + 0.78708 * group.width, y: group.minY + 0.67912 * group.height), controlPoint2: CGPoint(x: group.minX + 0.81633 * group.width, y: group.minY + 0.62641 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.97467 * group.width, y: group.minY + 0.66186 * group.height), controlPoint1: CGPoint(x: group.minX + 0.91239 * group.width, y: group.minY + 0.60811 * group.height), controlPoint2: CGPoint(x: group.minX + 0.95008 * group.width, y: group.minY + 0.63493 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.88454 * group.width, y: group.minY + 0.90887 * group.height), controlPoint1: CGPoint(x: group.minX + 1.04996 * group.width, y: group.minY + 0.77810 * group.height), controlPoint2: CGPoint(x: group.minX + 0.93842 * group.width, y: group.minY + 0.86608 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.77761 * group.width, y: group.minY + 0.99790 * group.height), controlPoint1: CGPoint(x: group.minX + 0.81522 * group.width, y: group.minY + 0.96786 * group.height), controlPoint2: CGPoint(x: group.minX + 0.77761 * group.width, y: group.minY + 0.99790 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.67047 * group.width, y: group.minY + 0.91216 * group.height), controlPoint1: CGPoint(x: group.minX + 0.77761 * group.width, y: group.minY + 0.99790 * group.height), controlPoint2: CGPoint(x: group.minX + 0.73268 * group.width, y: group.minY + 0.96622 * group.height))
        bezierPath.close()
        bianco.setStroke()
        bezierPath.lineWidth = 2
        bezierPath.lineCapStyle = .round
        bezierPath.stroke()


        if (highlited) {
            //// Bezier 2 Drawing
            let bezier2Path = UIBezierPath()
            bezier2Path.move(to: CGPoint(x: group.minX + 0.67050 * group.width, y: group.minY + 0.91225 * group.height))
            bezier2Path.addCurve(to: CGPoint(x: group.minX + 0.57942 * group.width, y: group.minY + 0.66195 * group.height), controlPoint1: CGPoint(x: group.minX + 0.57343 * group.width, y: group.minY + 0.84218 * group.height), controlPoint2: CGPoint(x: group.minX + 0.51199 * group.width, y: group.minY + 0.75421 * group.height))
            bezier2Path.addCurve(to: CGPoint(x: group.minX + 0.72154 * group.width, y: group.minY + 0.63159 * group.height), controlPoint1: CGPoint(x: group.minX + 0.62106 * group.width, y: group.minY + 0.61210 * group.height), controlPoint2: CGPoint(x: group.minX + 0.68025 * group.width, y: group.minY + 0.60653 * group.height))
            bezier2Path.addCurve(to: CGPoint(x: group.minX + 0.77763 * group.width, y: group.minY + 0.69676 * group.height), controlPoint1: CGPoint(x: group.minX + 0.73962 * group.width, y: group.minY + 0.64198 * group.height), controlPoint2: CGPoint(x: group.minX + 0.77060 * group.width, y: group.minY + 0.68505 * group.height))
            bezier2Path.addCurve(to: CGPoint(x: group.minX + 0.86058 * group.width, y: group.minY + 0.62089 * group.height), controlPoint1: CGPoint(x: group.minX + 0.78711 * group.width, y: group.minY + 0.67920 * group.height), controlPoint2: CGPoint(x: group.minX + 0.81636 * group.width, y: group.minY + 0.62650 * group.height))
            bezier2Path.addCurve(to: CGPoint(x: group.minX + 0.97470 * group.width, y: group.minY + 0.66195 * group.height), controlPoint1: CGPoint(x: group.minX + 0.91242 * group.width, y: group.minY + 0.60820 * group.height), controlPoint2: CGPoint(x: group.minX + 0.95010 * group.width, y: group.minY + 0.63502 * group.height))
            bezier2Path.addCurve(to: CGPoint(x: group.minX + 0.88456 * group.width, y: group.minY + 0.90895 * group.height), controlPoint1: CGPoint(x: group.minX + 1.04998 * group.width, y: group.minY + 0.77819 * group.height), controlPoint2: CGPoint(x: group.minX + 0.93844 * group.width, y: group.minY + 0.86617 * group.height))
            bezier2Path.addCurve(to: CGPoint(x: group.minX + 0.77763 * group.width, y: group.minY + 0.99798 * group.height), controlPoint1: CGPoint(x: group.minX + 0.81524 * group.width, y: group.minY + 0.96795 * group.height), controlPoint2: CGPoint(x: group.minX + 0.77763 * group.width, y: group.minY + 0.99798 * group.height))
            bezier2Path.addCurve(to: CGPoint(x: group.minX + 0.67050 * group.width, y: group.minY + 0.91225 * group.height), controlPoint1: CGPoint(x: group.minX + 0.77763 * group.width, y: group.minY + 0.99798 * group.height), controlPoint2: CGPoint(x: group.minX + 0.73270 * group.width, y: group.minY + 0.96630 * group.height))
            bezier2Path.close()
            rosso.setFill()
            bezier2Path.fill()
            rosso.setStroke()
            bezier2Path.lineWidth = 2
            bezier2Path.lineCapStyle = .round
            bezier2Path.stroke()
        }


        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRect(x: group.minX + fastFloor(group.width * 0.68903 + 0.5), y: group.minY + fastFloor(group.height * 0.00000 + 0.5), width: fastFloor(group.width * 0.81623 + 0.5) - fastFloor(group.width * 0.68903 + 0.5), height: fastFloor(group.height * 0.18367 + 0.5) - fastFloor(group.height * 0.00000 + 0.5)))
        bianco.setStroke()
        rectanglePath.lineWidth = 2
        rectanglePath.lineJoinStyle = .round
        rectanglePath.stroke()
    }

    @objc dynamic public class func drawMic(frame: CGRect = CGRect(x: 0, y: 0, width: 100, height: 100), highlited: Bool = true) {
        //// Color Declarations
        let bianco = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)

        //// Bezier 5 Drawing
        let bezier5Path = UIBezierPath()
        bezier5Path.move(to: CGPoint(x: frame.minX + 68.05, y: frame.minY + 20.24))
        bezier5Path.addCurve(to: CGPoint(x: frame.minX + 68.06, y: frame.minY + 20.83), controlPoint1: CGPoint(x: frame.minX + 68.06, y: frame.minY + 20.24), controlPoint2: CGPoint(x: frame.minX + 68.06, y: frame.minY + 20.44))
        bezier5Path.addCurve(to: CGPoint(x: frame.minX + 68.06, y: frame.minY + 55.12), controlPoint1: CGPoint(x: frame.minX + 68.06, y: frame.minY + 25.07), controlPoint2: CGPoint(x: frame.minX + 68.06, y: frame.minY + 50.87))
        bezier5Path.addCurve(to: CGPoint(x: frame.minX + 68.06, y: frame.minY + 55.71), controlPoint1: CGPoint(x: frame.minX + 68.06, y: frame.minY + 55.5), controlPoint2: CGPoint(x: frame.minX + 68.06, y: frame.minY + 55.71))
        bezier5Path.addCurve(to: CGPoint(x: frame.minX + 50.5, y: frame.minY + 73.44), controlPoint1: CGPoint(x: frame.minX + 67.75, y: frame.minY + 65.56), controlPoint2: CGPoint(x: frame.minX + 60.01, y: frame.minY + 73.44))
        bezier5Path.addCurve(to: CGPoint(x: frame.minX + 32.95, y: frame.minY + 55.71), controlPoint1: CGPoint(x: frame.minX + 40.99, y: frame.minY + 73.44), controlPoint2: CGPoint(x: frame.minX + 33.25, y: frame.minY + 65.56))
        bezier5Path.addCurve(to: CGPoint(x: frame.minX + 32.94, y: frame.minY + 55.12), controlPoint1: CGPoint(x: frame.minX + 32.94, y: frame.minY + 55.71), controlPoint2: CGPoint(x: frame.minX + 32.94, y: frame.minY + 55.5))
        bezier5Path.addCurve(to: CGPoint(x: frame.minX + 32.94, y: frame.minY + 20.83), controlPoint1: CGPoint(x: frame.minX + 32.94, y: frame.minY + 50.87), controlPoint2: CGPoint(x: frame.minX + 32.94, y: frame.minY + 25.07))
        bezier5Path.addCurve(to: CGPoint(x: frame.minX + 32.94, y: frame.minY + 20.24), controlPoint1: CGPoint(x: frame.minX + 32.94, y: frame.minY + 20.44), controlPoint2: CGPoint(x: frame.minX + 32.94, y: frame.minY + 20.24))
        bezier5Path.addCurve(to: CGPoint(x: frame.minX + 35.79, y: frame.minY + 10.82), controlPoint1: CGPoint(x: frame.minX + 33.05, y: frame.minY + 16.77), controlPoint2: CGPoint(x: frame.minX + 34.08, y: frame.minY + 13.54))
        bezier5Path.addCurve(to: CGPoint(x: frame.minX + 50.5, y: frame.minY + 2.5), controlPoint1: CGPoint(x: frame.minX + 38.92, y: frame.minY + 5.81), controlPoint2: CGPoint(x: frame.minX + 44.34, y: frame.minY + 2.5))
        bezier5Path.addCurve(to: CGPoint(x: frame.minX + 68.05, y: frame.minY + 20.24), controlPoint1: CGPoint(x: frame.minX + 60.01, y: frame.minY + 2.5), controlPoint2: CGPoint(x: frame.minX + 67.75, y: frame.minY + 10.39))
        bezier5Path.close()
        bezier5Path.move(to: CGPoint(x: frame.minX + 74.5, y: frame.minY + 55.71))
        bezier5Path.addCurve(to: CGPoint(x: frame.minX + 50.5, y: frame.minY + 79.95), controlPoint1: CGPoint(x: frame.minX + 74.5, y: frame.minY + 69.09), controlPoint2: CGPoint(x: frame.minX + 63.75, y: frame.minY + 79.95))
        bezier5Path.addCurve(to: CGPoint(x: frame.minX + 26.5, y: frame.minY + 55.71), controlPoint1: CGPoint(x: frame.minX + 37.25, y: frame.minY + 79.95), controlPoint2: CGPoint(x: frame.minX + 26.5, y: frame.minY + 69.09))
        bezier5Path.move(to: CGPoint(x: frame.minX + 51.09, y: frame.minY + 79.95))
        bezier5Path.addLine(to: CGPoint(x: frame.minX + 51.09, y: frame.minY + 96.5))
        bezier5Path.move(to: CGPoint(x: frame.minX + 39.38, y: frame.minY + 96.5))
        bezier5Path.addLine(to: CGPoint(x: frame.minX + 62.79, y: frame.minY + 96.5))
        bezier5Path.move(to: CGPoint(x: frame.minX + 68.65, y: frame.minY + 49.2))
        bezier5Path.addLine(to: CGPoint(x: frame.minX + 55.77, y: frame.minY + 49.2))
        bezier5Path.move(to: CGPoint(x: frame.minX + 68.65, y: frame.minY + 37.38))
        bezier5Path.addCurve(to: CGPoint(x: frame.minX + 55.77, y: frame.minY + 37.38), controlPoint1: CGPoint(x: frame.minX + 55.77, y: frame.minY + 37.38), controlPoint2: CGPoint(x: frame.minX + 55.77, y: frame.minY + 37.38))
        bezier5Path.move(to: CGPoint(x: frame.minX + 68.65, y: frame.minY + 25.56))
        bezier5Path.addCurve(to: CGPoint(x: frame.minX + 55.77, y: frame.minY + 25.56), controlPoint1: CGPoint(x: frame.minX + 55.72, y: frame.minY + 25.56), controlPoint2: CGPoint(x: frame.minX + 55.77, y: frame.minY + 25.56))
        bianco.setStroke()
        bezier5Path.lineWidth = 1
        bezier5Path.stroke()


        if (highlited) {
            //// Bezier Drawing
            let bezierPath = UIBezierPath()
            bezierPath.move(to: CGPoint(x: frame.minX + 68.05, y: frame.minY + 20.24))
            bezierPath.addCurve(to: CGPoint(x: frame.minX + 68.06, y: frame.minY + 20.83), controlPoint1: CGPoint(x: frame.minX + 68.06, y: frame.minY + 20.24), controlPoint2: CGPoint(x: frame.minX + 68.06, y: frame.minY + 20.44))
            bezierPath.addCurve(to: CGPoint(x: frame.minX + 68.06, y: frame.minY + 55.12), controlPoint1: CGPoint(x: frame.minX + 68.06, y: frame.minY + 25.07), controlPoint2: CGPoint(x: frame.minX + 68.06, y: frame.minY + 50.87))
            bezierPath.addCurve(to: CGPoint(x: frame.minX + 68.06, y: frame.minY + 55.71), controlPoint1: CGPoint(x: frame.minX + 68.06, y: frame.minY + 55.5), controlPoint2: CGPoint(x: frame.minX + 68.06, y: frame.minY + 55.71))
            bezierPath.addCurve(to: CGPoint(x: frame.minX + 50.5, y: frame.minY + 73.44), controlPoint1: CGPoint(x: frame.minX + 67.75, y: frame.minY + 65.56), controlPoint2: CGPoint(x: frame.minX + 60.01, y: frame.minY + 73.44))
            bezierPath.addCurve(to: CGPoint(x: frame.minX + 32.95, y: frame.minY + 55.71), controlPoint1: CGPoint(x: frame.minX + 40.99, y: frame.minY + 73.44), controlPoint2: CGPoint(x: frame.minX + 33.25, y: frame.minY + 65.56))
            bezierPath.addCurve(to: CGPoint(x: frame.minX + 32.94, y: frame.minY + 55.12), controlPoint1: CGPoint(x: frame.minX + 32.94, y: frame.minY + 55.71), controlPoint2: CGPoint(x: frame.minX + 32.94, y: frame.minY + 55.5))
            bezierPath.addCurve(to: CGPoint(x: frame.minX + 32.94, y: frame.minY + 20.83), controlPoint1: CGPoint(x: frame.minX + 32.94, y: frame.minY + 50.87), controlPoint2: CGPoint(x: frame.minX + 32.94, y: frame.minY + 25.07))
            bezierPath.addCurve(to: CGPoint(x: frame.minX + 32.94, y: frame.minY + 20.24), controlPoint1: CGPoint(x: frame.minX + 32.94, y: frame.minY + 20.44), controlPoint2: CGPoint(x: frame.minX + 32.94, y: frame.minY + 20.24))
            bezierPath.addCurve(to: CGPoint(x: frame.minX + 35.79, y: frame.minY + 10.82), controlPoint1: CGPoint(x: frame.minX + 33.05, y: frame.minY + 16.77), controlPoint2: CGPoint(x: frame.minX + 34.08, y: frame.minY + 13.54))
            bezierPath.addCurve(to: CGPoint(x: frame.minX + 50.5, y: frame.minY + 2.5), controlPoint1: CGPoint(x: frame.minX + 38.92, y: frame.minY + 5.81), controlPoint2: CGPoint(x: frame.minX + 44.34, y: frame.minY + 2.5))
            bezierPath.addCurve(to: CGPoint(x: frame.minX + 68.05, y: frame.minY + 20.24), controlPoint1: CGPoint(x: frame.minX + 60.01, y: frame.minY + 2.5), controlPoint2: CGPoint(x: frame.minX + 67.75, y: frame.minY + 10.39))
            bezierPath.close()
            bezierPath.move(to: CGPoint(x: frame.minX + 74.5, y: frame.minY + 55.71))
            bezierPath.addCurve(to: CGPoint(x: frame.minX + 50.5, y: frame.minY + 79.95), controlPoint1: CGPoint(x: frame.minX + 74.5, y: frame.minY + 69.09), controlPoint2: CGPoint(x: frame.minX + 63.75, y: frame.minY + 79.95))
            bezierPath.addCurve(to: CGPoint(x: frame.minX + 26.5, y: frame.minY + 55.71), controlPoint1: CGPoint(x: frame.minX + 37.25, y: frame.minY + 79.95), controlPoint2: CGPoint(x: frame.minX + 26.5, y: frame.minY + 69.09))
            bezierPath.move(to: CGPoint(x: frame.minX + 51.09, y: frame.minY + 79.95))
            bezierPath.addLine(to: CGPoint(x: frame.minX + 51.09, y: frame.minY + 96.5))
            bezierPath.move(to: CGPoint(x: frame.minX + 39.38, y: frame.minY + 96.5))
            bezierPath.addLine(to: CGPoint(x: frame.minX + 62.79, y: frame.minY + 96.5))
            bezierPath.move(to: CGPoint(x: frame.minX + 68.65, y: frame.minY + 49.2))
            bezierPath.addLine(to: CGPoint(x: frame.minX + 55.77, y: frame.minY + 49.2))
            bezierPath.move(to: CGPoint(x: frame.minX + 68.65, y: frame.minY + 37.38))
            bezierPath.addCurve(to: CGPoint(x: frame.minX + 55.77, y: frame.minY + 37.38), controlPoint1: CGPoint(x: frame.minX + 55.77, y: frame.minY + 37.38), controlPoint2: CGPoint(x: frame.minX + 55.77, y: frame.minY + 37.38))
            bezierPath.move(to: CGPoint(x: frame.minX + 68.65, y: frame.minY + 25.56))
            bezierPath.addCurve(to: CGPoint(x: frame.minX + 55.77, y: frame.minY + 25.56), controlPoint1: CGPoint(x: frame.minX + 55.72, y: frame.minY + 25.56), controlPoint2: CGPoint(x: frame.minX + 55.77, y: frame.minY + 25.56))
            UIColor.red.setStroke()
            bezierPath.lineWidth = 1
            bezierPath.stroke()
        }
    }

    //// Generated Images

    @objc dynamic public class func imageOfEvents(imageSize: CGSize = CGSize(width: 97, height: 99), highlited: Bool = true) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(imageSize, false, 0)
            StyleKit.drawEvents(frame: CGRect(x: 0, y: 0, width: imageSize.width, height: imageSize.height), highlited: highlited)

        let imageOfEvents = UIGraphicsGetImageFromCurrentImageContext()!.withRenderingMode(.alwaysOriginal)
        UIGraphicsEndImageContext()

        return imageOfEvents
    }

    @objc dynamic public class func imageOfMic(imageSize: CGSize = CGSize(width: 100, height: 100), highlited: Bool = true) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(imageSize, false, 0)
            StyleKit.drawMic(frame: CGRect(x: 0, y: 0, width: imageSize.width, height: imageSize.height), highlited: highlited)

        let imageOfMic = UIGraphicsGetImageFromCurrentImageContext()!.withRenderingMode(.alwaysOriginal)
        UIGraphicsEndImageContext()

        return imageOfMic
    }

}
